-- Legal Contract Review Demo - Snowflake Setup
-- Run with role: SS_ADMIN_ROLE

USE ROLE SS_ADMIN_ROLE;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS LEGAL_CONTRACT_DEMO;

CREATE SCHEMA IF NOT EXISTS LEGAL_CONTRACT_DEMO.RAW;
CREATE SCHEMA IF NOT EXISTS LEGAL_CONTRACT_DEMO.ANALYTICS;
CREATE SCHEMA IF NOT EXISTS LEGAL_CONTRACT_DEMO.APP;

-- Internal stage for contract PDFs
CREATE STAGE IF NOT EXISTS LEGAL_CONTRACT_DEMO.RAW.CONTRACT_STAGE
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- Contract text content
CREATE OR REPLACE TABLE LEGAL_CONTRACT_DEMO.RAW.CONTRACT_TEXT (
  CONTRACT_ID VARCHAR,
  FILENAME VARCHAR,
  CONTRACT_TYPE VARCHAR,
  FULL_TEXT VARCHAR(16777216),
  UPLOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Clause-level analysis results from Cortex AI
CREATE OR REPLACE TABLE LEGAL_CONTRACT_DEMO.ANALYTICS.CLAUSE_ANALYSIS (
  CLAUSE_ID VARCHAR DEFAULT UUID_STRING(),
  CONTRACT_ID VARCHAR,
  CLAUSE_TYPE VARCHAR,
  CLAUSE_TEXT VARCHAR(16777216),
  ASSIGNED_TEAM VARCHAR,
  RISK_LEVEL VARCHAR,
  RISK_EXPLANATION VARCHAR(16777216),
  REVIEW_STATUS VARCHAR DEFAULT 'pending',
  ANALYZED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Contract-level summary
CREATE OR REPLACE TABLE LEGAL_CONTRACT_DEMO.ANALYTICS.CONTRACT_SUMMARY (
  CONTRACT_ID VARCHAR,
  CONTRACT_NAME VARCHAR,
  CONTRACT_TYPE VARCHAR,
  PARTIES VARCHAR,
  EFFECTIVE_DATE VARCHAR,
  EXPIRATION_DATE VARCHAR,
  OVERALL_RISK VARCHAR,
  SUMMARY_TEXT VARCHAR(16777216),
  KEY_FINDINGS VARIANT,
  TEAM_REVIEW_STATUS VARIANT,
  ANALYZED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Service stage for SPCS spec files
CREATE STAGE IF NOT EXISTS LEGAL_CONTRACT_DEMO.APP.SERVICE_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- Image repository for Docker images
CREATE IMAGE REPOSITORY IF NOT EXISTS LEGAL_CONTRACT_DEMO.APP.IMAGE_REPO;
